### ISSUE TITLE
Improve `PricingEvaluatorUtil` message exceptions

### ISSUE THREAD

**Issue by pgmarc** [isa-group/Pricing4Java#55]
Given this yaml file with an errata expression of `havePetsDashboard`:

```yaml
features:
  havePetsDashboard:
    valueType: BOOLEAN
    defaultValue: false
    expression: planContext['features']['petDashboard']
   // expression: planContext['features']['havePetsDashboard'] Should be use this instead
    type: DOMAIN
```

This message is logged to console. The only information that provide is that something went wrong:

```txt
2025-04-28T09:41:54.158+02:00  WARN 21564 --- [nio-8080-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [io.github.isagroup.exceptions.PricingPlanEvaluationException: Evaluation was null]
```
